version: 0.2

phases:
  pre_build:
    commands:
      - bash scripts/aws/codebuild-env.sh
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  build:
    commands:
      - bash scripts/aws/docker-build-push.sh
      - bash scripts/aws/ec2-deploy.sh
